version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  mongo:
    image: "mongo:3.6"
    ports:
     - "27017:27017"
  web:
    build: .
    image: ob/reference-mock-server
    ports:
     - "8001:8001"